### ISSUE TITLE
Upload fails on Linux due to Mac-specific script in platformio.ini

### ISSUE THREAD

**Issue by dustin-richards-was-here** [daniloc/PicoW_HomeAssistant_Starter#1]
My Linux system complains that osascript doesn't exist in the post-upload step, due to mac-post-upload.py. Could platformio.ini be set up to only run this step on Mac systems? Or maybe add an OS check to mac-post-upload.py?

I was able to get the upload to work by just removing the script from platformio.ini.

(I may submit a pull request for this later, just wanted to throw it out there in case someone else wanted to get to it before me since it's probably not too complicated)

**Comment by daniloc** [comment]
@dustin-richards-was-here thanks so much for raising this!
