### ISSUE TITLE
Extraneous MQTT Switch

### ISSUE THREAD

**Issue by JacobChrist** [daniloc/PicoW_HomeAssistant_Starter#9]
Initial issue was that not all HASwitches were showing up:

``` c++
HASwitch led("led");
HASwitch zone[] = { 
    HASwitch("Zone0"),
    HASwitch("Zone1"),
    HASwitch("Zone2"),
    HASwitch("Zone3"),
    HASwitch("Zone4"),
    HASwitch("Zone5"),
    HASwitch("Zone6"),
    HASwitch("Zone7"),
    HASwitch("Zone8"),
    HASwitch("Zone9"),
};
```
(snip)
``` c++
    // handle switch state
    led.onCommand(switchHandler);
    led.setName("FlowBot LED"); // optional

    // Zone state
    for(uint8_t i = 0; i < 10; i++)
    {
        zone[i].onCommand(switchHandler);
    }
    zone[0].setName("Zone 0"); // optional
    zone[1].setName("Zone 1"); // optional
    zone[2].setName("Zone 2"); // optional
    zone[3].setName("Zone 3"); // optional
    zone[4].setName("Zone 4"); // optional
    zone[5].setName("Zone 5"); // optional
    zone[6].setName("Zone 6"); // optional
    zone[7].setName("Zone 7"); // optional
    zone[8].setName("Zone 8"); // optional
    zone[9].setName("Zone 9"); // optional
```
![image](https://github.com/daniloc/PicoW_HomeAssistant_Starter/assets/198251/1e0604c4-c370-422c-bb8d-f45267677b13)

And for some reason one of the switches comes up unnamed ("MQTT Switch").

**Comment by JacobChrist** [comment]
Found what was limiting the number of HASwitches and changed the maxDeviceTypeNB to resolve:

```
    explicit HAMqtt(
        Client& netClient,
        HADevice& device,
        const uint8_t maxDevicesTypesNb = 12
    );
```

However I still have a extra non-responsive MQTT Switch

**Comment by JacobChrist** [comment]
I'm wondering if this is not an issue in HA itself.  When I added another HASwitch then removed it, it now appears in the settings but is no longer in code "FlowBot ABC".  Maybe its a string left in the MQTT server.
![image](https://github.com/daniloc/PicoW_HomeAssistant_Starter/assets/198251/0791bbbc-83fe-439f-aae3-995edafaea3b)

**Comment by JacobChrist** [comment]
Interestingly enough, the names of the Entity created is based on when I created the entity and what I was doing at the time of creation.  That is to say they are named inconsistently and this may be related: For example:

 
![image](https://github.com/daniloc/PicoW_HomeAssistant_Starter/assets/198251/16b6ba5a-c8fa-4db6-b0c2-871062170042) vs ![image](https://github.com/daniloc/PicoW_HomeAssistant_Starter/assets/198251/2237db76-5038-4a3a-aaac-d1865e9e9061)

Zone 3 was around before I figure out how to name the zones and get more than 6 switches so it got a generic name.  Zone 4 was first created with a name after the max number of devices was created.

The two non-working switches have names associated with switches I created then removed while testing different confiturations:

![image](https://github.com/daniloc/PicoW_HomeAssistant_Starter/assets/198251/2c2c146a-cc72-421d-a6da-35bcac68dc52) ![image](https://github.com/daniloc/PicoW_HomeAssistant_Starter/assets/198251/e15e36a9-ce7d-460a-9ddb-faa1ae6a7384)

I've tried to delete entities but I get this message:

![image](https://github.com/daniloc/PicoW_HomeAssistant_Starter/assets/198251/12b0dbea-9f60-4384-9e4d-506d0649b10e)

```
Only 0 selected entities can be removed.
You can only remove 0 of the selected 1 entities. Entities can only be removed when the integration is no longer providing the entities. Sometimes you have to restart Home Assistant before you can remove the entities of a removed integration. Are you sure you want to remove the removable entities?
```

**Comment by daniloc** [comment]
Good catch on `maxDevicesTypesNb`. This is another one where I think you'll get further working directly with the maintainers of Arduino Home Assistant. This project is just an example to show how to get started using it. This issue, for example, [came up just last week](https://github.com/dawidchyrzynski/arduino-home-assistant/issues/162).

**Comment by JacobChrist** [comment]
I'm pretty sure this is an issue with HA and the way MQTT caches messages.  If I delete the device then the issue goes away.
![image](https://github.com/daniloc/PicoW_HomeAssistant_Starter/assets/198251/6b5ce78c-4924-428b-a293-64f5450b4679)

Also, all the Entity ID's update to the correct names set in firmware.
![image](https://github.com/daniloc/PicoW_HomeAssistant_Starter/assets/198251/7dec80c7-153d-4014-b7b0-900ab3a9fad2)

**Comment by JacobChrist** [comment]
I'm pretty sure this is an issue with HA and the way MQTT caches messages.  If I delete the device then the issue goes away.
![image](https://github.com/daniloc/PicoW_HomeAssistant_Starter/assets/198251/6b5ce78c-4924-428b-a293-64f5450b4679)

Also, all the Entity ID's update to the correct names set in firmware.
![image](https://github.com/daniloc/PicoW_HomeAssistant_Starter/assets/198251/7dec80c7-153d-4014-b7b0-900ab3a9fad2)
